version: '3'
services:
  yalba-db:
    image: postgres:latest
    restart: always
    container_name: yalba-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # TODO: add prisma service and connect postgres to yalba

  yalba-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    # image: t3-app
    container_name: yalba-app
    environment:
      DATABASE_URL: "localhost" # hello yes fix this